export const metadata = {
    title: "ARTIISNINC",
    description: "Generated by create next app",
    manifest: "/manifest.json",
    themeColor: "#8936FF",
    icons: {
      icon: [
        { src: "/icon512_maskable.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
        { src: "/icon512_rounded.png", sizes: "512x512", type: "image/png", purpose: "any" }
      ]
    },
    background_color: "#2EC6FE",
  };
  